version: '3'
services:
  db:
    image: postgres:latest
    container_name: rsvp_db_postgres
    environment:
      - POSTGRES_USER=${db_user}  
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host} 
    ports:
      - "5435:5432"
  rsvp:
    image: rsvp:latest
    container_name: rsvp_app
    working_dir: /go/src/rsvp
    command: ["go", "run", "main.go"]
    ports:
      - "8080:8080"
    restart: on-failure
    links:
      - db
    depends_on:
      - db